# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A0Tci8yyppQ8X-JyPmwdDusvJWsUajxN
"""

def verificarnumero(numero):

  lista=[]
  if len(numero)>4 or len(numero)<4:
    print("el número sí y solo sí puede ser de cuatro dígitos")
  elif "0" in numero:
    print("el número no puede contener el dígito cero")
  else:
    for i in numero:
      if i in lista:
        print("los digitos del número no se pueden repetir")
        break
      else:
        lista.append(i)
  if len(lista)==4:
    return False
  else:
    return True

print("jugador 1: ")
validar=True
while validar==True:
  numero=input("Ingrese un número de cuatro digitos que no se repita ni tenga 0 en él ")
  validar=verificarnumero(numero)
  numeroj1=numero
print("jugador 2: ")
validar=True
while validar==True:
  numero=input("Ingrese un número de cuatro digitos que no se repita ni tenga 0 en él ")
  validar=verificarnumero(numero)
  numeroj2=numero



print("Comienza el juego")
ganador=False
while ganador==False:
  print("Jugador 1 adivina el número del rival")

  validar=True
  while validar==True:
    numero=input("Ingrese un número de cuatro digitos que no se repita ni tenga 0 en él ")
    validar=verificarnumero(numero)
    turno=numero
  fijas=0
  picas=0
  for i in range(4):
    if numeroj2[i]==turno[i]:
      fijas+=1
    elif turno[i] in numeroj2:
      picas+=1
  print("fijas: ",fijas)
  print("picas: ",picas)
  if fijas==4:
    print("Jugador 1 has ganado")
    break

  print("Jugador 2 adivina el número del rival")
  validar=True
  while validar==True:
    numero=input("Ingrese un número de cuatro digitos que no se repita ni tenga 0 en él ")
    validar=verificarnumero(numero)
    turno=numero
  fijas=0
  picas=0
  for i in range(4):
    if numeroj1[i]==turno[i]:
      fijas+=1
    elif turno[i] in numeroj1:
      picas+=1
  print("fijas: ",fijas)
  print("picas: ",picas)
  if fijas==4:
    print("Jugador 2 has ganado")
    break